CREATE TABLE `campaign_report` (
  `id` int(11) UNSIGNED NOT NULL,
  `day` varchar(50) DEFAULT NULL,
  `accountId` int(11) DEFAULT NULL,
  `accountName` varchar(100) DEFAULT NULL,
  `advertiserId` int(11) DEFAULT NULL,
  `advertiserName` varchar(100) DEFAULT NULL,
  `campaignId` varchar(50) DEFAULT NULL,
  `campaignName` varchar(250) DEFAULT NULL,
  `campaignStartDate` varchar(100) DEFAULT NULL,
  `campaignEndDate` varchar(100) DEFAULT NULL,
  `siteId` int(11) DEFAULT NULL,
  `siteName` varchar(250) DEFAULT NULL,
  `adId` varchar(50) DEFAULT NULL,
  `adName` varchar(250) DEFAULT NULL,
  `placementId` varchar(50) DEFAULT NULL,
  `placementName` varchar(250) DEFAULT NULL,
  `adFormatName` varchar(150) DEFAULT NULL,
  `placementDimension` varchar(250) DEFAULT NULL,
  `sectionName` varchar(150) DEFAULT NULL,
  `costPerUnit` bigint(20) DEFAULT NULL,
  `impression` bigint(20) DEFAULT NULL,
  `clicks` bigint(20) DEFAULT NULL,
  `totalConvertion` bigint(20) DEFAULT NULL,
  `postClickConversion` bigint(20) DEFAULT NULL,
  `postImpresionConversion` bigint(20) DEFAULT NULL,
  `conversionRevenue` bigint(20) DEFAULT NULL,
  `totalMediaCost` double DEFAULT NULL,
  `ecpc` double DEFAULT NULL,
  `ecpa` double DEFAULT NULL,
  `ecpm` double DEFAULT NULL,
  `totalProfit` double DEFAULT NULL,
  `placementNameSplit_1` varchar(150) DEFAULT NULL,
  `placementNameSplit_2` varchar(150) DEFAULT NULL,
  `placementNameSplit_3` varchar(150) DEFAULT NULL,
  `placementNameSplit_4` varchar(150) DEFAULT NULL,
  `placementNameSplit_5` varchar(120) DEFAULT NULL,
  `placementNameSplit_6` varchar(150) DEFAULT NULL,
  `placementNameSplit_7` varchar(150) DEFAULT NULL,
  `placementNameSplit_8` varchar(150) DEFAULT NULL,
  `placementNameSplit_9` varchar(150) DEFAULT NULL,
  `conversion_name_1` varchar(350) DEFAULT NULL,
  `conversion_value_1` double DEFAULT NULL,
  `conversion_name_2` varchar(350) DEFAULT NULL,
  `conversion_value_2` double DEFAULT NULL,
  `conversion_name_3` varchar(350) DEFAULT NULL,
  `conversion_value_3` double DEFAULT NULL,
  `conversion_name_4` varchar(350) DEFAULT NULL,
  `conversion_value_4` double DEFAULT NULL,
  `conversion_name_5` varchar(350) DEFAULT NULL,
  `conversion_value_5` double DEFAULT NULL,
  `conversion_name_6` varchar(350) DEFAULT NULL,
  `conversion_value_6` double DEFAULT NULL,
  `conversion_name_7` varchar(350) DEFAULT NULL,
  `conversion_value_7` double DEFAULT NULL,
  `conversion_name_8` varchar(350) DEFAULT NULL,
  `conversion_value_8` double DEFAULT NULL,
  `conversion_name_9` varchar(350) DEFAULT NULL,
  `conversion_value_9` double DEFAULT NULL,
  `in_date` datetime DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `campaign_report`
ADD PRIMARY KEY (`id`);

ALTER TABLE `campaign_report`
MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=0;

----------------

CREATE TABLE `campaign_version` (
  `id` int(11) UNSIGNED NOT NULL,
  `day` date DEFAULT NULL,
  `accountId` int(11) DEFAULT NULL,
  `accountName` varchar(100) DEFAULT NULL,
  `advertiserId` int(11) DEFAULT NULL,
  `advertiserName` varchar(100) DEFAULT NULL,
  `campaignId` varchar(50) DEFAULT NULL,
  `campaignName` varchar(250) DEFAULT NULL,
  `campaignStartDate` varchar(100) DEFAULT NULL,
  `campaignEndDate` varchar(100) DEFAULT NULL,
  `siteId` int(11) DEFAULT NULL,
  `siteName` varchar(250) DEFAULT NULL,
  `adId` varchar(50) DEFAULT NULL,
  `adName` varchar(250) DEFAULT NULL,
  `placementId` varchar(50) DEFAULT NULL,
  `placementName` text,
  `adFormatName` varchar(150) DEFAULT NULL,
  `placementDimension` varchar(250) DEFAULT NULL,
  `versionName` varchar(250) DEFAULT NULL,
  `targetAudienceName` varchar(100) DEFAULT NULL,
  `sectionName` varchar(200) NOT NULL,
  `impression` bigint(20) DEFAULT NULL,
  `clicks` bigint(20) DEFAULT NULL,
  `totalConversion` bigint(20) DEFAULT NULL,
  `conversionRevenue` bigint(20) DEFAULT NULL,
  `postClickConversion` bigint(20) DEFAULT NULL,
  `postImpresionConversion` bigint(20) DEFAULT NULL,
  `versNameSplit_1` varchar(150) DEFAULT NULL,
  `versNameSplit_2` varchar(150) DEFAULT NULL,
  `versNameSplit_3` varchar(150) DEFAULT NULL,
  `versNameSplit_4` varchar(150) DEFAULT NULL,
  `versNameSplit_5` varchar(120) DEFAULT NULL,
  `versNameSplit_6` varchar(150) DEFAULT NULL,
  `versNameSplit_7` varchar(120) DEFAULT NULL,
  `versNameSplit_8` varchar(120) DEFAULT NULL,
  `versNameSplit_9` varchar(150) DEFAULT NULL,
  `conversion_name_1` varchar(350) DEFAULT NULL,
  `conversion_value_1` double DEFAULT NULL,
  `conversion_name_2` varchar(350) DEFAULT NULL,
  `conversion_value_2` double DEFAULT NULL,
  `conversion_name_3` varchar(350) DEFAULT NULL,
  `conversion_value_3` double DEFAULT NULL,
  `conversion_name_4` varchar(350) DEFAULT NULL,
  `conversion_value_4` double DEFAULT NULL,
  `conversion_name_5` varchar(350) DEFAULT NULL,
  `conversion_value_5` double DEFAULT NULL,
  `conversion_name_6` varchar(350) DEFAULT NULL,
  `conversion_value_6` double DEFAULT NULL,
  `conversion_name_7` varchar(350) DEFAULT NULL,
  `conversion_value_7` double DEFAULT NULL,
  `conversion_name_8` varchar(350) DEFAULT NULL,
  `conversion_value_8` double DEFAULT NULL,
  `conversion_name_9` varchar(350) DEFAULT NULL,
  `conversion_value_9` double DEFAULT NULL,
  `in_date` datetime DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `campaign_version`
ADD PRIMARY KEY (`id`);

ALTER TABLE `campaign_version`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=0;

---------------------------
CREATE TABLE `campaign_unique` (
  `id` int(11) UNSIGNED NOT NULL,
  `accountId` int(11) DEFAULT NULL,
  `accountName` varchar(100) DEFAULT NULL,
  `advertiserId` int(11) DEFAULT NULL,
  `advertiserName` varchar(100) DEFAULT NULL,
  `campaignId` varchar(50) DEFAULT NULL,
  `campaignName` varchar(250) DEFAULT NULL,
  `campaignStartDate` varchar(100) DEFAULT NULL,
  `campaignEndDate` varchar(100) DEFAULT NULL,
  `siteId` int(11) DEFAULT NULL,
  `siteName` varchar(250) DEFAULT NULL,
  `adId` varchar(50) DEFAULT NULL,
  `adName` varchar(250) DEFAULT NULL,
  `placementId` varchar(50) DEFAULT NULL,
  `placementName` varchar(250) DEFAULT NULL,
  `adFormatName` varchar(150) DEFAULT NULL,
  `placementDimension` varchar(250) DEFAULT NULL,
  `sectionName` varchar(150) DEFAULT NULL,
  `costPerUnit` bigint(20) DEFAULT NULL,
  `impression` bigint(20) DEFAULT NULL,
  `clicks` bigint(20) DEFAULT NULL,
  `totalConversion` bigint(20) DEFAULT NULL,
  `postClickConversion` bigint(20) DEFAULT NULL,
  `postImpresionConversion` bigint(20) DEFAULT NULL,
  `conversionRevenue` bigint(20) DEFAULT NULL,
  `totalMediaCost` double DEFAULT NULL,
  `uniqueImpression` double DEFAULT NULL,
  `uniqueClicks` double DEFAULT NULL,
  `averageFrequensy` double DEFAULT NULL,
  `uniqueVideoStartd` double DEFAULT NULL,
  `uniqueInteraction` double DEFAULT NULL,
  `adAverageDuration` double DEFAULT NULL,
  `videoStart` double DEFAULT NULL,
  `videoPlayed25` double DEFAULT NULL,
  `videoPlayed50` double DEFAULT NULL,
  `videoPlayed75` double DEFAULT NULL,
  `videoPlayedFull` double DEFAULT NULL,
  `videoAverageDuration` double DEFAULT NULL,
  `placementNameSplit_1` varchar(150) DEFAULT NULL,
  `placementNameSplit_2` varchar(150) DEFAULT NULL,
  `placementNameSplit_3` varchar(150) DEFAULT NULL,
  `placementNameSplit_4` varchar(150) DEFAULT NULL,
  `placementNameSplit_5` varchar(120) DEFAULT NULL,
  `placementNameSplit_6` varchar(150) DEFAULT NULL,
  `placementNameSplit_7` varchar(120) DEFAULT NULL,
  `placementNameSplit_8` varchar(120) DEFAULT NULL,
  `placementNameSplit_9` varchar(150) DEFAULT NULL,
  `in_date` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `campaign_unique`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `campaign_unique`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=0;

-----------------------

CREATE TABLE `campaign_video` (
  `id` int(11) UNSIGNED NOT NULL,
  `day` varchar(50) DEFAULT NULL,
  `accountId` int(11) DEFAULT NULL,
  `accountName` varchar(100) DEFAULT NULL,
  `advertiserId` int(11) DEFAULT NULL,
  `advertiserName` varchar(100) DEFAULT NULL,
  `campaignId` varchar(50) DEFAULT NULL,
  `campaignName` varchar(250) DEFAULT NULL,
  `campaignStartDate` varchar(100) DEFAULT NULL,
  `campaignEndDate` varchar(100) DEFAULT NULL,
  `siteId` int(11) DEFAULT NULL,
  `siteName` varchar(250) DEFAULT NULL,
  `adId` varchar(50) DEFAULT NULL,
  `adName` varchar(250) DEFAULT NULL,
  `placementId` varchar(50) DEFAULT NULL,
  `placementName` varchar(250) DEFAULT NULL,
  `adFormatName` varchar(150) DEFAULT NULL,
  `placementDimension` varchar(250) DEFAULT NULL,
  `sectionName` varchar(150) DEFAULT NULL,
  `costPerUnit` bigint(20) DEFAULT NULL,
  `impression` bigint(20) DEFAULT NULL,
  `clicks` bigint(20) DEFAULT NULL,
  `totalConversion` bigint(20) DEFAULT NULL,
  `postClickConversion` bigint(20) DEFAULT NULL,
  `postImpresionConversion` bigint(20) DEFAULT NULL,
  `conversionRevenue` bigint(20) DEFAULT NULL,
  `totalMediaCost` double DEFAULT NULL,
  `ecpc` double DEFAULT NULL,
  `ecpa` double DEFAULT NULL,
  `ecpm` double DEFAULT NULL,
  `totalProfit` double DEFAULT NULL,
  `adAverageDuration` double DEFAULT NULL,
  `videoStart` double DEFAULT NULL,
  `videoPlayed25` double DEFAULT NULL,
  `videoPlayed50` double DEFAULT NULL,
  `videoPlayed75` double DEFAULT NULL,
  `videoPlayedFull` double DEFAULT NULL,
  `videoAverageDuration` double DEFAULT NULL,
  `placementNameSplit_1` varchar(150) DEFAULT NULL,
  `placementNameSplit_2` varchar(150) DEFAULT NULL,
  `placementNameSplit_3` varchar(150) DEFAULT NULL,
  `placementNameSplit_4` varchar(150) DEFAULT NULL,
  `placementNameSplit_5` varchar(120) DEFAULT NULL,
  `placementNameSplit_6` varchar(150) DEFAULT NULL,
  `placementNameSplit_7` varchar(120) DEFAULT NULL,
  `placementNameSplit_8` varchar(120) DEFAULT NULL,
  `placementNameSplit_9` varchar(150) DEFAULT NULL,
  `in_date` datetime DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `campaign_video`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `campaign_video`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=0;
